version: '2'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    container_name: maktaba_drupal
    entrypoint: ./drupal-entrypoint.sh
    command: [apache2-foreground]
    networks:
      - private-network

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/exports:/docker-entrypoint-initdb.d
    networks:
      - private-network
  solr:
    restart: on-failure
    image: twinbit/docker-drupal-solr
    hostname: solr
    ports:
      - "8983:8983"
    command: -Xmx1024m -DSTOP.PORT=8079 -DSTOP.KEY=stopkey -jar start.jar

networks:
  private-network:
    driver: bridge
