<?php
/**
* Implements hook_entity_property_info_alter().
*
* Adds an entity property for the domain access of the node.
*/

function custom_entity_property_info_alter(&$info) {

  $properties = &$info['node']['properties'];

  $properties['custom_domain_access'] = array(
    'label' => t('Domain Access Information'),
    'description' => t('The domains to which the node is published.'),
    'type' => 'list<integer>',
    'getter callback' => 'custom_get_domain_info',
  );
}

function custom_get_domain_info($data, array $options, $name, $type, $info) {
  return (!empty($data->domains) ? $data->domains : NULL);
}

/**
* Implements hook_search_api_query_alter().
*
* Adds a filter for the current domain.
*/
/*
function custom_search_api_query_alter(SearchApiQueryInterface $query) {

  $domain = domain_get_domain();
  $query->condition('custom_domain_access', $domain['domain_id']);
      
}*/
